version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t dougt1/demo .
      - docker tag dougdemo:latest 717840979392.dkr.ecr.eu-west-1.amazonaws.com/dougdemo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 717840979392.dkr.ecr.eu-west-1.amazonaws.com/dougdemo:latest





