version: 0.1

environment_variables:
  plaintext:
    DOCKER_HUB_USERNAME: "your-Docker-Hub-user-name"
    DOCKER_HUB_PASSWORD: "your-Docker-Hub-password"
    IMAGE_REPO_NAME: "your-Docker-Hub-repo-name"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username="$DOCKER_HUB_USERNAME" --password="$DOCKER_HUB_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
