version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login)
                - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
            build:
              commands:
                - docker build --tag "717840979392.dkr.ecr.eu-west-1.amazonaws.com/dougdemo:latest" .
            post_build:
              commands:
                - docker push "717840979392.dkr.ecr.eu-west-1.amazonaws.com/dougdemo:latest"
                - printf '{"tag":"%s"}' $TAG > build.json
